### ISSUE TITLE
Visitor count request taking too long

### ISSUE THREAD

**Issue by ar51an** [ESKYoung/shields-io-visitor-counter#16]
Hi,
I am using this visitor counter for few months. Everything was working fine. Today the request is taking too long and within github page it times out.

Here is a screenshot of your own page. Same thing is happening with all my repos:

![image](https://user-images.githubusercontent.com/11185794/204112265-4674348a-43bf-4363-ab3d-6ffba0253eb8.png)

**Comment by ESKYoung** [comment]
Hi @ar51an, thanks for raising the issue!

Yep this is down to Heroku - I thought I had more time today to deal with this, so apologies for the downtime!

Essentially, [Heroku have dropped their free plans](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq), which is why you've experienced downtime. Note any visits during this downtime won't be counted. 

I've started a paid plan for this app now, so it should be working now. 

Going forward, I'll have to assess the viability of paying for Heroku, or migrating to anything service etc. but I'll give fair warning for doing so (couple of months) for migrations etc.

**Comment by ar51an** [comment]
Thank you @ESKYoung

Got it, appreciate the quick response and details about  the issue.
